# Generated by Django 4.2.1 on 2023-09-24 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название анкеты')),
                ('description', models.TextField(verbose_name='Описание анкеты')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='SelfFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Отзыв руководителя о себе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв руководителя о себе',
                'verbose_name_plural': 'Отзывы руководителей о себе',
            },
        ),
        migrations.CreateModel(
            name='ManagerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Отзыв о руководителе')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о руководителе',
                'verbose_name_plural': 'Отзывы о руководителях',
            },
        ),
        migrations.CreateModel(
            name='EmployeeFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Анонимный пользователь')),
                ('feedback', models.TextField(verbose_name='Отзыв о сотруднике')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Оценка')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о сотруднике',
                'verbose_name_plural': 'Отзывы о сотрудниках',
            },
        ),
        migrations.CreateModel(
            name='ColleagueFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Отзыв о коллегах')),
                ('colleagues', models.ManyToManyField(related_name='colleague_feedback', to=settings.AUTH_USER_MODEL, verbose_name='Коллеги')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв о коллегах',
                'verbose_name_plural': 'Отзывы о коллегах',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_user', models.CharField(blank=True, max_length=255, null=True, verbose_name='Анонимный пользователь')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerating.questionnaire', verbose_name='Анкета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='AccessRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view_answers', models.BooleanField(default=False, verbose_name='Просмотр ответов')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerating.questionnaire', verbose_name='Анкета')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Права доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
    ]
